// Code ControlledInput Component Here

// two ways of getting values in form elements

// 1. UNCONTROLLED
// 2. CONTROLLED

// IF COMPONENT HAS A VALUE PROP- IT IS CONTROLLED
// IF IT DOES NOT HAVE ONE, OR HAS A defaultVALUE PROP IT IS UNCRONTROLLED

// UNCONTROLLED
// THE FORM ELEMENT IN QUESTION HAS ITS OWN INTERNAL STATE
// TO RETRIVE WE NEEED TO ACCESS THE DOM COMPONENT THAT HOLDS THAT VALUE, OR WE HAVE TO ADD AN onCHANGE HANDLER
// TO SET AN INITIAL VALUE FOR THE ELEMENT WE'D USE THE defaultVALUE PROP

// CONTROLLED
// EXPLICITLY SET THE VALUE OF A COMPONENT AND UPDATE THAT VALUE IN RESPONSE TO ANY CHANGES THE USER MAKES TO THE VALUE OF THAT COMPONENT. 
